# dataset config
gpu_id: 0
state: INFO
seed: 2022
field_separator: "\t"
data_path: 'dataset/'
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
LABEL_FIELD: label
drop_filter_field: True

metrics: ["Recall", "NDCG", "Hit", "P_Fair","GiniIndex","TailPercentage"]
topk: [20]
train_batch_size: 4096
eval_batch_size: 40960000
valid_metric: NDCG@20
epochs: 1000
stopping_step: 20
learning_rate: 1e-4

# fairness_type: ada2fair
provider_eta: 2
user_eta: 1
delta: 1e-7
weight_epochs: 10

#train_batch_size训练时的批量大小 控制每次输入模型的数据量
#eval_batch_size: 40960000：评估时的批量大小，这个值较大，可能是为了在一次评估中处理尽可能多的数据。